version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mylinkedin_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqlvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
  
volumes:
  mysqlvol:
    external: true
