"""Add last name.

Revision ID: 98f72e3f4ebc
Revises: a6b04502f983
Create Date: 2020-10-07 16:12:24.724327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f72e3f4ebc'
down_revision = 'a6b04502f983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
